### ISSUE TITLE
Submit to F-droid repo as well?

### ISSUE THREAD

**Issue by ph1l** [itemir/signalk-mobile#1]
For those of us without any closed source google apps on their android phones?

https://f-droid.org/ -- F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. The client makes it easy to browse, install, and keep track of updates on your device.

**Comment by itemir** [comment]
I wasn't familiar with f-droid but submitted an inclusion request: https://f-droid.org/forums/topic/signal-k-mobile-app/ Hope it will suffice.
